### ISSUE TITLE
roadmap: checklist

### ISSUE THREAD

**Issue by twilson63** [hyper63/workshop-api#15]
## Movies

- [x] - POST /api/movies
- [x] - POST /api/movies/_search
- [x] - GET /api/movies/{id}
- [x] - PUT /api/movies/{id}
- [x] - DELETE /api/movies/{id}
- [x] - GET /api/movies/{id}/reviews

## Reviews

- [x] - POST /api/reviews
- [x] - GET /api/reviews
- [x] - GET /api/reviews/{id}
- [x] - PUT /api/reviews/{id}
- [x] - DELETE /api/reviews/{id}

## Reactions

- [x] - POST /api/reactions
- [x] - GET /api/reviews/{id}/reactions
